### ISSUE TITLE
Does it work with Mattermost 5.20.1 and PHP-FPM 7.3 ?

### ISSUE THREAD

**Issue by jcharaoui** [Crivaledaz/Mattermost-LDAP#41] opened 2020-03-14 14:46 UTC
I've been trying hard to deploy this on a Debian 10 server with Apache 2.4 and PHP-FPM 7.3, but so far I haven't had any luck. Being unfamiliar with oauth2 in general probably doesn't help. The LDAP part works fine, and I can see access tokens show up in the database, but it seems it's hitting problems when interacting with the Matthermost instance.

Looking at the OAuth2 source code, it seems like it was designed for the era of PHP 5.x, so it's unclear if I'm just wasting my time or perhaps someone else has had success making it work on a modern stack?

I also had a shot at oauth2_proxy with Azure as a provider but there again, I don't know if it's that's even a logical option.

**Comment by b3** [comment] 2020-04-02 23:36
Is it someting like #43?

**Comment by Crivaledaz** [comment] 2020-04-05 21:13
Hi,

You are right, Mattermost-LDAP has been implemented for PHP 5.6. The module is based on the Oauth2 PHP implementation made by bshaffer (https://github.com/bshaffer/oauth2-server-php). In 2017, when I began the module, I took the last realease of his project, which was verion 1.9.0. I never took the time to update Mattermost-LDAP with new versions of bshaffer project. Maybe I will have the time during the lockdown ;)

Nevertheless, I have re-installed Mattermost and Mattermost-LDAP on my PC, and I can confirm that Mattermost-LDAP is working with Mattermost Team Edition 5.21.0 and PHP-FPM 7.3. 

Here, my configuration in details :

| Component | Version |
|-----------|---------|
| Fedora    | 31      |
| PostgreSQL | 11.7 |
| Mattermost | 5.21.0 |
| Httpd | 2.4.41 |
| PHP-FPM | 7.3.16 |

Let me know where you are stuck, what kind of error do you get ?

Regards,

**Comment by Crivaledaz** [comment] 2020-04-30 18:04
Hi,

I finally found some time during the lockdown, and I have worked on a new Mattermost-LDAP version. So, I am glad to announce Mattermost-LDAP V2 is now in beta :) 

This new version includes an update of [bshaffer's Oauth server implementation](https://github.com/bshaffer/oauth2-server-php). Mattermost-LDAP is now fully complaint with PHP 7, as you can see in the [demo](https://github.com/Crivaledaz/Mattermost-LDAP/tree/v2/Demo).

You can try this new version from the branch [v2](https://github.com/Crivaledaz/Mattermost-LDAP/tree/v2). For more informations about this version, see the [changelog file](https://github.com/Crivaledaz/Mattermost-LDAP/blob/v2/changelog.md)

Please, let me know if this new version solves your issue.

Regards

**Comment by jcharaoui** [comment] 2020-04-30 18:08
Thanks for working on this! As far as I'm concerned I've moved to to another project, but I'm quite certain this work will be useful for others. Feel free to close this issue.

**Comment by Crivaledaz** [comment] 2020-06-30 10:55
I close this issue since PHP 7 is supported in Mattermost-LDAP V2.

**Closed by Crivaledaz** 2020-06-30 10:55 UTC
